### ISSUE TITLE
Airfoil Leading Edge co-ordinate

### ISSUE THREAD

**Issue by sakibsadman7** [IEAWindTask37/IEA-3.4-130-RWT#1]
Hi Dr. Pietro
Hope you are well.

I just had a query regarding the airfoil definitions of 3.4MW.  According to standard airfoil definitions, the leading edge usually has a coordinate of (x,y) = (0,0). But for these airfoils they don't have that, is there any particular reason for that?

Best
Sadman Sakib
The University of Texas at Dallas

**Comment by ptrbortolotti** [comment]
Dear Sadman,
thanks for your message and the interest in the model. The airfoil data should have a 0,0 point. Do you refer to the .yaml file? If so, to which airfoil?
Thanks again and best regards,
Pietro

**Comment by sakibsadman7** [comment]
Dear Dr. Pietro
Thank you for your reply. These airfoils in both the YAML file and the excel sheet are having the issue,
DU97-W-300, DU00-W2-350, FX77-W-400, FX77-W-500.

**Comment by ptrbortolotti** [comment]
Dear Sadman,
I've just checked, and in the .yaml file the profiles DU97-W-300 and DU00-W2-350 do have the leading edge located at 0,0...
The airfoils FX77-W-400 and FX77-W-500 are instead defined translated. This is indeed not the standard way of defining airfoils, but it helped to obtain a smooth lofted shape of the blade. You can translate them back, but you need to remember to correct the moment coefficient.
I hope this helps.
Best regards,
Pietro

**Comment by sakibsadman7** [comment]
Dear Dr. Pietro

Thank you for your help.

Best
Sadman
