### ISSUE TITLE
Rotor Inertia

### ISSUE THREAD

**Issue by eletroinf** [IEAWindTask37/IEA-3.4-130-RWT#10]
Hello
Do you have the value of the Rotor Inertia (given by one of the OpenFAST .sum files)?
I need this parameter to complete a simplified model.

Regards,
Ricardo

**Comment by ptrbortolotti** [comment]
Hello Ricardo,
28762547.943 kg-m^2. You can compute this value yourself running OpenFAST 3.2 or 3.3 (https://github.com/OpenFAST/openfast/releases/tag/v3.3.0) and turning on this flag https://github.com/IEAWindTask37/IEA-3.4-130-RWT/blob/1e6c1e4db7428badc553dd55226aa1ee2c4ab47b/openfast/IEA-3.4-130-RWT_ElastoDyn.dat#L110
I'll close the issue, please reopen it if something isn't clear.
Regards,
Pietro
