### ISSUE TITLE
OpenFAST Simulink Warnings IEA 

### ISSUE THREAD

**Issue by vicemora** [IEAWindTask37/IEA-3.4-130-RWT#11]
I'm running  OpenFAST Simunlink with the  3.5.0 version. How ever, I encountered so much warnings 
such as this:

Warning: block 'OpenLoop/FAST Nonlinear Wind Turbine/S-Function':
FAST_Solution:CalcOutputs_And_SolveForInputs:SolveOption2:AD_CalcOutput:RotCalcOutput:BEMT_CalcOutput(node
2, blade 1):UA_CalcOutput:UA_BlendSteady:Temporarily turning off UA due to high angle of attack or low
relative velocity. This warning will not be repeated though the condition may persist. 

at the last one this;
Warning: block 'OpenLoop/FAST Nonlinear Wind Turbine/S-Function':
FAST_Solution:CalcOutputs_And_SolveForInputs:SolveOption2:AD_CalcOutput:RotCalcOutput:BEMT_CalcOutput(node
30, blade 2):UA_CalcOutput:Mach number exceeds 0.3. Theory is invalid. This warning will not be
repeated though the condition may persist.

I'm trying to design a controller based on RL, In the simulation I'm using the default configuration, using a steady wind and using the controller within the repo (I was just making tries), I don't know if these warning will affect my results :( 
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/bced5d70-7b13-432a-b850-b5796d51be64)

I say that because, I do not why the power is 0, if the model initializes the rotor velocity at a value of 5 rpm.

I'm sorry I'm a begginer at the software

**Comment by vicemora** [comment]
I'm trying to run with version 3.0 as stated in another issue but I can't. What version do u recommend, I'm trying to implement a controller based on RL, using Simulink S function

**Comment by ptrbortolotti** [comment]
hello,
those warnings might suggest that you have a bad initial condition and/or your controller is not initialized correctly. Have you tried running the model with ROSCO https://github.com/NREL/ROSCO, that should give you a good benchmark. I have never run this model with a controller in Simulink actually

**Comment by vicemora** [comment]
Thanks! I'll try it. 
I have been making tries changing simulation parameters. I want to know why you can't initialize the rotor velocity with a value of zero. It gives me some warnings and wrong output data.
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/4adcac21-149a-4710-b038-0851bc10c46e)
I mean, don't the rotor velocity zero indicates that the WT is simulated from rest? Why you should set a velocity diff from zero for the simulation to run properly?

**Comment by ptrbortolotti** [comment]
ROSCO does not implement accurate start-up maneuvers and it's common to start simulations with a non zero rpm
