### ISSUE TITLE
Control Regions

### ISSUE THREAD

**Issue by vicemora** [IEAWindTask37/IEA-3.4-130-RWT#12]
Hello! 
I'm testing the Uni Flensburg - David Schlipf controller. I want to test only region 3 winds.
First, how do you recomend to set the initial rpm of the WT for this?
Second, I wanted to see how the system will behave if the pitch controller is set to none (and the generator controller is the DS controller). But for some reason, even in region 3, the torque controller is trying to maintain the power. This is not valid, because for mantaining the power, the velocity of the rotor is greater than its recommended max value. I want to know how to ensure the torque generator controller will work only below rated wind velocity and pitch controller will work only above rated wind velocity (region 3)
Thanks!

**Comment by vicemora** [comment]
it will be also help full to know the    Blade edgewise first natural frequency [rad/s] and  Blade flapwise first natural frequency [rad/s].
I'm trying to tune the ROSCO Controller for this model

**Comment by vicemora** [comment]
Can you provide me with a IEA3.4.yaml Example FILE for tuning in ROSCO. I need some variables I can't find in the documentation.
I cannot find these: 
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/aa9d32db-aa5a-4606-9b82-5b85f2c10c75)

**Comment by vicemora** [comment]
Update: I tried to use the DISCON.IN file within the repo and the .dll of the ROSCO  2.7.0 but I have a problem, The pitch angle is being controller below rated speed. 
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/a708e78c-6a4b-4dc0-a313-a76a7df15d92)

This is not supposed to happen, I set the setpoint below rated at 0 deg help plz

**Comment by ptrbortolotti** [comment]
The values that you are requesting predicted by WISDEM (https://github.com/WISDEM/WISDEM) are:
Rotor inertia around shaft axis: 2.87e7 kg m2
1st blade flap freq: 0.792 Hz
1st blade edge freq: 1.07 Hz

I can't really speak about the controller from the University of Flensburg. Prof Schlipf might be able to help there http://www.znes-flensburg.de/person/schlipf-david?language=en

ROSCO should work fine, please double check your inputs

**Comment by vicemora** [comment]
Dear @ptrbortolotti  
Thanks for the information. 
The controller in the photo is the ROSCO. But I did not get the .IN file by my own, instead I use the one that is in the repo in the openFAST directory (it says it works with ROSCO 2.7.0).
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/94f17a98-caa1-41fd-aee0-367a89bcfc9c)
That is the performance I get. As I stated is weird that the pitch angle is not zero below rated conditions, even when I specify the pitch angle setpoint below rate as 0. I'm trying to use the ROSCO as the benchmark for my project.

I want  to know if you have the **.yaml file required to ROSCO** for creating/tunning the IEA 3.4MW controller. I'm trying to create the .yaml file, but I do not have any example for a land-based WT. There are a lot of examples for off-shore WT differing in many parameters each one. Since I do not have a lot of expertise I'm suffering with that task. 

Or if you have an idea about how to fix the issue of the controller (the pitch angle is not zero below rated conditions).

**Comment by ptrbortolotti** [comment]
Hello again,
I don't have the yaml file to tune ROSCO (we tune it automatically using WISDEM). But I'm surprised that you're looking for that file. ROSCO v2.7.0 is already tuned with this file https://github.com/IEAWindTask37/IEA-3.4-130-RWT/blob/master/openfast/IEA-3.4-130-RWT_DISCON.IN, why would you want to retune it?
I've just tried running a quick simulation with a steady inflow of 4 m/s https://github.com/IEAWindTask37/IEA-3.4-130-RWT/blob/c036f783b160604b133a2e4b7317320fde055743/openfast/IEA-3.4-130-RWT_InflowFile.dat#L14 and the rotor isn't pitching. Please check your inputs. What wind speed are you using?

**Comment by vicemora** [comment]
Hello @ptrbortolotti 
I wanted to retune because of the pitch problem. I'm using 10 m/s as the wind speed because I'm working at rated conditions. 
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/41dbecbc-70fe-441a-993a-d68a582516be)

With that wind, the rotor keeps pitching before rated conditions
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/45ab58d7-c307-41ac-8369-6fdc09760bf5)
setpoint below rated is zero and initial pitch angles are all zeros. I do not known what is going on, I don't even know if it can be solved,

**Comment by ptrbortolotti** [comment]
I believe that's the peak thrust shaving option of the controller. you can turn it off by setting to 0 line 16 of the DISCON. however loads will go unrealistically high

**Comment by vicemora** [comment]
Thanks. One last thing: my RL pitch controller should minimize loads. I have to create a reward function that will help the system learn to minimize loads.

So here is my question: when you do pitch control, which variable of OpenFAST would you assess to validate that your controller minimizes the load? I'm asking for a recommendation based on your expertise. After this, I'll close the issue.

**Comment by ptrbortolotti** [comment]
The peak thrust shaving reduces the max rotor thrust measured at the hub. The individual pitch controller, which is something else and it is not activated in this version of ROSCO, minimizes off-axis moments at the hub

**Comment by vicemora** [comment]
Thank you so much for your help. The first my approach of my project is to design a RL based collective pitch controller. Does collective pitch controller helps minimizing any kind of loads I can measure in OpenFAST?

**Comment by ptrbortolotti** [comment]
Collective pitch aims at maximizing power below rated wind speed and at keeping power constant above. The only exception is around rated where blade pitch is used to limit max thrust
