### ISSUE TITLE
ServoDyn and DISCON 

### ISSUE THREAD

**Issue by vicemora** [IEAWindTask37/IEA-3.4-130-RWT#13]
Hello @ptrbortolotti 
I want to use the ROSCO controller using the bladed interface in Servodyn.
If you have ever used this controller, can you tell me if this configuration is correct? I want a standard performance according to the values in the IEA 3.4 130 documentation; nothing fancy.
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/e0218e50-0f12-493b-bce7-7881eaff5362)

Also, I've noticed there are some parameters in the servodyn bladed interface section that are also in the DISCON.IN file. Which parameters were finally taken into consideration in the simulation? Those in servodyn or those in the DISCON.IN file?. Do you have any documents or references to go into depth on this topic?

Happy holidays!

**Comment by ptrbortolotti** [comment]
Happy Holidays to you as well. What you show looks correct. Note however that you don't need to retune ROSCO, you can simply call the existing DISCON. As long as PCcontrol and VSControl are set to 5 in ServoDyn, the external DISCON from ROSCO is called, and not much of ServoDyn is used

**Comment by ptrbortolotti** [comment]
as for documentation, please refer to the online documentation of openfast and ServoDyn
