### ISSUE TITLE
About Torque Controller ROSCO

### ISSUE THREAD

**Issue by vicemora** [IEAWindTask37/IEA-3.4-130-RWT#14]
Helo @ptrbortolotti 
I have a question about the torque control using ROSCO.
I had set the controller to set a constant torque in region III.
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/a018a9bd-d628-45bf-b4d3-f7b40769056e)
Here are also the VSControl parameters:
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/2175b053-4885-4808-84d6-783acc2b3c08)

I'm implementing a controller based on deep learning and reinforcement learning. Since I'm focusing on region 3, is it expected the torque in region 3 to be constant and set to its rated value. However, in some simulations, the torque controller goes beyond its rated value. That is not the expected behavior, according to the controller.
I want to know why this is happening. Have you experienced this before? What are the possible causes?
What should I do to prevent this to hapend?

**Comment by dzalkind** [comment]
I would suggest using `VS_ControlMode` of 2.  This seems like a ROSCO issue and we'd be happy to help you on [that GitHub page](https://github.com/NREL/ROSCO).

**Comment by vicemora** [comment]
Thank you so much! It works!
