### ISSUE TITLE
About load values.

### ISSUE THREAD

**Issue by vicemora** [IEAWindTask37/IEA-3.4-130-RWT#15]
Hi @ptrbortolotti 
I'm designing a SCADA system for the IEA 3.4 WT. One of the sections in the load section. 
Since the SCADA is oriented to look at "pitch control" effect I'm presenting as lodas: blade-root bending moment, shaft bending moments at the main bearing, and tower-top and tower-base bending and yaw moments. 
I-m willing to define a "Turbine's health section" based on the values of the defined loads. Is there something like normal operation values/max values for the loads I'm considering?

**Comment by vicemora** [comment]
I mean how do I know if a load is high or if it is in its expected value?

**Comment by ptrbortolotti** [comment]
hello @vicemora, appendix A.6 in https://www.nrel.gov/docs/fy19osti/73492.pdf report some load envelopes. Note however that these were obtained during the design phase, so not with OpenFAST and not with ROSCO. Unfortunately we never had the bandwidth to run (nor document) a detailed load evaluation for this turbine in OpenFAST + ROSCO. My suggestion is to run the baseline model with the baseline ROSCO yourself and characterize the baseline loads

**Comment by vicemora** [comment]
Thank you @ptrbortolotti. I did not noticed that tables.I need to ensure that the loads do not exceed the max allowable values. 
Just to ensure that I'm not misunderstanding the tables, for example: 
![image](https://github.com/IEAWindTask37/IEA-3.4-130-RWT/assets/56892117/6a18a5c7-45b4-4658-9287-5e19f8c5339d)
The first highlighted value mean that "My" should not exceed 1.04E+07 at blade3. Am I misunderstaing the table? 
If I'm, what would be the correct way to establish a limit for "My" and how do I know where?

**Comment by ptrbortolotti** [comment]
The table lists a load envelope. You can read it like this. First row: when Fx is maximum, the other load components (Fx Fy Fz Mx My Mz) are these values. Max Fx is recorded on Blade 2 during DLC 1.3 at 13 m/s at second 266.4 and it includes a safety factor of 1.35. The second raw is about minimum Fx, and so on. The diagonal of the table reports the max of each load channel (although these max values don't occur all at the same time nor on the same blade!)
