### ISSUE TITLE
OutListParameters.xlsx missing

### ISSUE THREAD

**Issue by joanaurbano6** [IEAWindTask37/IEA-3.4-130-RWT#16]
Hello!

I was trying to run the IEA-3.4-130-RWT turbine with the rosco controller, using the ROSCO matlab toolbox and ROSCO simulink and noticed that the input files IEA-3.4-130-RWT_AeroDyn15.dat, IEA-3.4-130-RWT_InflowFile.dat and IEA-3.4-130-RWT_ServoDyn.dat have their outlist empty. 
In these files it says: "See OutListParameters.xlsx for a listing of available output channels, (-)", but I can't find this excel anywhere.  I checked the IEAonshore.xlsx. but there is no info about the output parameters. 

Could anyone provide me this excel please?

**Comment by ptrbortolotti** [comment]
https://github.com/OpenFAST/openfast/blob/main/docs/OtherSupporting/OutListParameters.xlsx

**Comment by joanaurbano6** [comment]
> https://github.com/OpenFAST/openfast/blob/main/docs/OtherSupporting/OutListParameters.xlsx

Thanks a lot! :)
