### ISSUE TITLE
Rated generator torque in technical report and DISCON.IN

### ISSUE THREAD

**Issue by joanaurbano6** [IEAWindTask37/IEA-3.4-130-RWT#17]
Hello,

I am using the IEA3.4MW for my master thesis and I am having trouble understanding the units in generator torque:
- In the table 7 in the technical report, the rated torque is 2.925 MNm (which would correspond to 2925000 Nm);
- In the IEAonshore.xlsx excel, Look Up Table WT States (in WTControl page), the rated torque is also 2.925MNm;
- In the DISCON.IN file (line 72), the rated torque is 29075.20 Nm.
Is there an error in the units of the DISCON.IN file? Am I interpreting something wrong?  I don't understand this discrepancy 

Thank you very much in advance for your time!

**Comment by ptrbortolotti** [comment]
I believe there is a typo in the DISCON.IN file, where rated torque is expressed in kNm. Please go ahead with 2.925 MNm

**Comment by ptrbortolotti** [comment]
I'm sorry, I was very wrong with my previous reply. Everything is correct. The DISCON is in Nm. The DISCON expresses the generator torque, which is 29075 Nm, whereas the 2.925MNm is the aerodynamic torque measured at the hub

**Comment by joanaurbano6** [comment]
I understand now! 
Thanks a lot
