### ISSUE TITLE
High Angle of Attack followed by ** Shutdown **

### ISSUE THREAD

**Issue by sedesed** [IEAWindTask37/IEA-3.4-130-RWT#4]
I'm new to GitHub--hopefully I am posting in the right place. I recently upgraded from Fastv8 to OpenFAST 2.3, downloaded the IEA-3.4-RWT files, and have been using the ROSCO controller as suggested. However, when running the IEA-3.4-130-RWT.fst file (all other input files also unchanged) the controller keeps pitching the blades to 90deg/Shutdown Mode: 

     Running ElastoDyn.
     Running AeroDyn.
     Running BEM.
     Running UnsteadyAero.
     Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 1, Blade = 1
     Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 1, Blade = 2
     Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 1, Blade = 3
     Running InflowWind.
     Running ServoDyn.
     Running ServoDyn Interface for Bladed Controllers.
      Time: 0 of 60 seconds.
       ** SHUTDOWN MODE **
     
     FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SrvD_CalcOutput:
     ------------------------------------------------------------------------------
     Running a controller implemented through NREL's ROSCO Toolbox
     A wind turbine controller framework for public use in the scientific field
     Developed in collaboration: National Renewable Energy Laboratory
                                 Delft University of Technology, The Netherlands
     Primary development by (listed alphabetically): Nikhar J. Abbas
                                                     Sebastiaan P. Mulders
                                                     Jan-Willem van Wingerden
     Visit our GitHub-page to contribute to this project:
     https://github.com/NREL/ROSCO
     -----------------------------------------------------------------------------
     
                                                                                                       
      Time: 5 of 60 seconds. Estimated final completion at 16:20:36.
     Warning: Turning off Unsteady Aerodynamics due to high angle of attack (-45.03 deg). BladeNode =
     30, Blade = 2
.
.
repeats message for blades/nodes
.
.
     Warning: Turning off Unsteady Aerodynamics due to high angle of attack (-45.03 deg). BladeNode =
     24, Blade = 3
       ** SHUTDOWN MODE **
     Generator speed:  180.0 RPM, Pitch angle:  70.0 deg, Power:     0.0 kW, Est. wind Speed:   4.8 m/s
                                                                                                       
      Time: 10 of 60 seconds. Estimated final completion at 16:20:35.
     Warning: Turning off Unsteady Aerodynamics due to high angle of attack (-45.065 deg). BladeNode =
     28, Blade = 2
.
.
repeats message for blades/nodes
.
.
     Warning: Turning off Unsteady Aerodynamics due to high angle of attack (-45.029 deg). BladeNode =
     14, Blade = 3
                                                                                                       
      Time: 15 of 60 seconds. Estimated final completion at 16:20:34.
       ** SHUTDOWN MODE **
     Generator speed:   67.2 RPM, Pitch angle:  90.0 deg, Power:     0.0 kW, Est. wind Speed:   1.9 m/s
                                                                                                       
      Time: 20 of 60 seconds. Estimated final completion at 16:20:32.
                                                                                                       
      Time: 25 of 60 seconds. Estimated final completion at 16:20:33.
       ** SHUTDOWN MODE **
     Generator speed:   17.1 RPM, Pitch angle:  90.0 deg, Power:     0.0 kW, Est. wind Speed:   0.6 m/s
                                                                                                       
      Time: 30 of 60 seconds. Estimated final completion at 16:20:33.
                                                                                                       
      Time: 35 of 60 seconds. Estimated final completion at 16:20:33.
       ** SHUTDOWN MODE **
     Generator speed:    3.8 RPM, Pitch angle:  90.0 deg, Power:     0.0 kW, Est. wind Speed:   0.2 m/s
                                                                                                       
      Time: 40 of 60 seconds. Estimated final completion at 16:20:33.
                                                                                                       
      Time: 45 of 60 seconds. Estimated final completion at 16:20:33.
       ** SHUTDOWN MODE **
     Generator speed:    2.9 RPM, Pitch angle:  90.0 deg, Power:     0.0 kW, Est. wind Speed:   0.1 m/s
                                                                                                       
      Time: 50 of 60 seconds. Estimated final completion at 16:20:33.
                                                                                                       
      Time: 55 of 60 seconds. Estimated final completion at 16:20:33.
       ** SHUTDOWN MODE **
     Generator speed:    2.9 RPM, Pitch angle:  90.0 deg, Power:     0.0 kW, Est. wind Speed:   0.2 m/s
                                                                                                       
      Time: 60 of 60 seconds. Estimated final completion at 16:20:33.

I can't seem to find any existing troubleshooting advice besides changing initial conditions, but I am not sure how to change them or what to change to improve this besides changing initial blade pitch or wind speed? I think I am doing something wrong as this seems to be a functioning model. I am also not sure I understand how the "Est. wind Speed" is changing when I am using steady, 5m/s as was already selected/entered in the InflowWind file.

(I have some experience with Fastv8 as I took a 1 semester class on it, but it's obviously limited).

I haven't included any of the files/code because they are all 100% unchanged from the download.

**Comment by ptrbortolotti** [comment]
Hi, yes you're in the right place. Let's see if I can help you.
It seems that the simulation starts, and after a few instants the ROSCO controller pushes the machine into shutdown. This is likely because your initial conditions are outside the operating range of the machine. 

To start, I'd check the initial rotor speed, defined in ElastoDyn here
https://github.com/IEAWindTask37/IEA-3.4-130-RWT/blob/5291cc44c6fdbf33c5c72421e02353f1f35d82e5/openfast/IEA-3.4-130-RWT_ElastoDyn.dat#L35

You can also turn off the shutdown logic, by playing with this flag
https://github.com/IEAWindTask37/IEA-3.4-130-RWT/blob/5291cc44c6fdbf33c5c72421e02353f1f35d82e5/openfast/IEA-3.4-130-RWT_DISCON.IN#L17

If this does not help, check the Inflow Wind file. Keep the WindType to 1
https://github.com/IEAWindTask37/IEA-3.4-130-RWT/blob/5291cc44c6fdbf33c5c72421e02353f1f35d82e5/openfast/IEA-3.4-130-RWT_InflowFile.dat#L5

And this steady state wind speed:
https://github.com/IEAWindTask37/IEA-3.4-130-RWT/blob/5291cc44c6fdbf33c5c72421e02353f1f35d82e5/openfast/IEA-3.4-130-RWT_InflowFile.dat#L12

I hope this helps.

Good luck,
Pietro

**Comment by sedesed** [comment]
Hi Pietro,

I appreciate your response! I've checked all of these things and they appear to be fine/as suggested. I even re-downloaded all of the files to be sure I hadn't accidentally changed anything. Turning off shutdown mode (SD_Mode = 0) still results in the blades pitching to 90deg and the wind speed slowing in the first minute, and staying near 0.2m/s as long as I have let it run (up to 3 min). I've also run through different initial rotor speeds with the same result. I did just notice this warning comes first, even before the ROSCO controller. Sorry, it just got buried in the warnings before: 

> Running ElastoDyn.
> Running AeroDyn.
> Running BEM.
> Running UnsteadyAero.
> Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 1, Blade = 1
> Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 1, Blade = 2
> Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 1, Blade = 3
> Running InflowWind.
> Running ServoDyn.
> Running ServoDyn Interface for Bladed Controllers.

then ROSCO runs and we get the repeated Turning off Unsteady Aerodynamics due to high angle of attack warnings, generator slows, blades pitch to 90, 0 power, wind speed around 0.2m/s. (with SD_mode = 0). I understand what you mean about initial conditions being outside of the operating range, but I could use some more guidance on what my options are to toggle/change.


Thanks,

Sarah

**Comment by ptrbortolotti** [comment]
Hi Sarah,

in the f/beamdyn branch of this repository I've just pushed the model compatible to the very latest OpenFAST (2.4.0) and generated by the latest version of WISDEM (3.0.3)

https://github.com/IEAWindTask37/IEA-3.4-130-RWT/tree/f/BeamDyn

I've tested this model with the ROSCO controller (https://github.com/NREL/ROSCO/tree/master) and everything works fine

I'd suggest switching to the newest files and give it another try.

I hope this helps

Pietro

**Comment by anikshah43** [comment]
Hi Pietro,

I am using the recommended model from the [https://github.com/IEAWindTask37/IEA-3.4-130-RWT/tree/f/BeamDyn] with OpenFAST(2.4.0) and the ROSCO controller. However, I end up with the following error - PC_GS_angles must be non-decreasing.

![image](https://user-images.githubusercontent.com/76649689/145033772-c59cb17d-6766-40b9-8d34-d097938641cf.png)

I had multiple adapted DISCON.IN files as well as the Cq_Cp_Ct.txt files from TU Munich (I am a new PhD student here) and also from you but end up with the same error. Could you provide me with a working version or advice me as to how this error can be resolved. 

Thank you in advance,
Anik

**Comment by ptrbortolotti** [comment]
Hello Anik,
unfortunately I've never found the time to check the issues raised here https://github.com/IEAWindTask37/IEA-3.4-130-RWT/issues/2 and so the beamdyn branch is lingering and not been merged.
This said, I've just updated the openfast model to OpenFAST 3.0, and I've refreshed the model in several aspects, among which the DISCON.IN file. Things should run fine. 
Note that if you're planning to run BeamDyn, it might be a good idea to use this fork/branch of openfast https://github.com/ptrbortolotti/openfast/tree/beamdyn_io, which implements some corrections to BeamDyn
If you tell me more, here or via email, of what you're planning to do, I might be able to say more.
Good luck!
Pietro

**Comment by anikshah43** [comment]
Hi Pietro,

Thank you for your email. As it turns out, I found a DISCON.In file
modified here at TUM to work with the model for Openfast 2.4.0. I tested it
to steady wind inflow and seems to work well. I will work with this for
turbulent winds and see if it responds fine. My goal is to actually use
this model in SOWFA to carry out LES. Eventually, I want to run this model
in FASTv8 as our implementation of SOWFA is linked with FASTv8. I imagine I
would have to modify the input files quite a bit for that. Is there perhaps
any other way to get there?

Best regards,
Anik

**Comment by ptrbortolotti** [comment]
Hello Anik,
I'm afraid you'll have to work your way through the files manually. Hopefully the API changes aren't too many.
I assume you'll use ElastoDyn with SOWFA... In fact, I would not 100% trust the implementation of BeamDyn in fastv8.
Best,
Pietro
