### ISSUE TITLE
openFAST blade mass doesn't match

### ISSUE THREAD

**Issue by phil-brad** [IEAWindTask37/IEA-3.4-130-RWT#5]
The blade mass properties in `IEA-3.4-130-RWT_ElastoDyn_blade.dat` don't seem to match what is in the spreadsheet. With trapezium integration (having applied the `AdjBlMs` factor), I get a total mass 15,215kg per blade, whereas the spreadsheet states it is 16,441kg. I can't seem to find a reason for the discrepancy (e.g. removing non-structural mass) when comparing the distribution from the spreadsheet with what's in the Elastodyn file. Is there a good reason for the difference?

![image](https://user-images.githubusercontent.com/35700541/109244506-710dbe00-77a4-11eb-8a1f-6cb4d23fac36.png)

**Comment by ptrbortolotti** [comment]
Hi phil-brad,
thanks for your interest in the IEA 3.4MW RWT.

You raise some good points. Let's start from the spreadsheet lines. The yellow line (structural only) consists of the mass that the cross sectional analysis tool from TUM (ANBA) computed. On top of it, we added extra materials, such as sandwich fillers, lightening protection system, adhesive, extra resin. The total blade mass distribution is the blue line, you should use that one.

Now about FAST vs spreadsheet: while the spreadsheets were generated at TUM in Germany, the FAST files were generated one/two years later at NREL using the tool WEIS (https://github.com/WISDEM/WEIS). We did the conversion at the blade structure level, and not at the equivalent beam level, so although we tried our best, differences in blade mass distribution still exist. 

Note that the input file to WEIS https://github.com/IEAWindTask37/IEA-3.4-130-RWT/blob/master/yaml/IEA-3.4-130-RWT.yaml respects the windIO guidelines (click here for more details https://github.com/IEAWindTask37/windIO).

I hope this helps.
Best regards,
Pietro

**Comment by phil-brad** [comment]
Hi Pietro

Thanks for your response - makes sense. Given that I am running with FAST, it would therefore make sense to update its mass distribution to run with the true model. Do you think this can be done risk free?

Philip
