### ISSUE TITLE
HAWC2 shear parameters off by 9 orders of magnitude

### ISSUE THREAD

**Issue by jennirinker** [IEAWindTask37/IEA-3.4-130-RWT#6]
Currently, the columns corresponding to the shear parameter kx and ky are in the range of E+06 to E+09. However, this value is normally closer to about 0.5. Perhaps an error in the scripts used to convert the yaml to HAWC2?

**Comment by jennirinker** [comment]
cc @fanzhongmeng

**Comment by RRiva** [comment]
I think that Fanzhong used the fact that in HAWC2 the shear stiffnesses are kx * G * A and ky * G * A, so it does not matter what you enter in each number, as long as the product is correct. In the st file I can see that both G and A are 1, so he placed all the information in kx and ky.

**Comment by jennirinker** [comment]
Yes, I just realized that and will therefore close. Thanks for the quick response!
