### ISSUE TITLE
OpenFAST version to run IEA 3.4

### ISSUE THREAD

**Issue by BenTreeD** [IEAWindTask37/IEA-3.4-130-RWT#7]
Hi,
I am wondering with which version of OpenFast I can run this example? I have been comparing the versions and tried to update the input files according to the documentation, however without success so far. For example when using OpenFast 2.0.0 I get the error of an unvalid input of the variable UseBlCm in AeroDyn, however this variable has not been changed according to the documentation. 
I'd really appriciate your help. thanks! 

Cheers, 
Ben

**Comment by ptrbortolotti** [comment]
Hi,
have you tried openfast 3.0?
Otherwise on this branch https://github.com/IEAWindTask37/IEA-3.4-130-RWT/tree/f/BeamDyn I've just updated the files to openfast 3.1 and the raaw branch of ROSCO.
I hope this helps.
Best regards,
Pietro
