### ISSUE TITLE
DT & Gen. efficiency

### ISSUE THREAD

**Issue by avus01** [IEAWindTask37/IEA-3.4-130-RWT#9]
Hello everyone,

In the [documentation](https://www.nrel.gov/docs/fy19osti/73492.pdf), I found the value for the DT & Gen. efficiency $\eta$ to be 93.6%. 
Now, when I check `IEA-3.4-130-RWT_ElastoDyn.dat`, I find a gearbox efficiency $\eta_{DT}$ of 95% in the drivetrain section.
In `IEA-3.4-130-RWT_ServoDyn_WT1.dat`, I find a generator efficiency $\eta_{Gen}$ of 97.95%.

I am expecting $\eta = \eta_{DT}\eta_{Gen}$, however, multiplying the two values found in these .dat files yields 93.0525%.
The error is small and probably negligible but I am hoping you can still help me to clarify this.

**Comment by ptrbortolotti** [comment]
Hello Arnold,
thank you for spotting this inconsistency. The source of the error is in the input data to GeneratorSE coming from the ontology yaml. I've now commented all these inputs in the yaml file and hard coded the previous efficiency of 98.08% as specified in the technical report. Note that we've recently done some work with GeneratorSE (https://github.com/WISDEM/GeneratorSE/tree/dev) and it would be nice to find the time to redesign this nacelle. DrivetrainSE also needs some long-awaited improvements.
All in all, for the time being I recommend going ahead with 98.08% of generator efficiency and 95.5% of gearbox efficiency for a combined efficiency of 93.67%
Good luck!
Pietro

**Comment by avus01** [comment]
Hello Pietro,
Thanks a lot for your quick response! 
I will adjust the values as you are suggesting. 
Looking forward for these improvements.
